name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
  runs-on: ubuntu-latest
  
  steps:
    # Check out repository code
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
    run: echo Hello,world!
    
    
    
  
  
  
  
