name: test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          #repository: peiyi870425/my_project #commercial-mgcp/
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
    
