on:
  push:
    tags:
      - 'v*.*.*'
env:
  RELEASE_VERSION2: ${GITHUB_REF#refs/*/}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: $RELEASE_VERSION2-docs.tar.gz
        run:
          echo $RELEASE_VERSION2